Some Tweaks To #7
TeamTerminus/MachineEssentials pull request #9
Opened 2024-11-07 17:36 UTC by calmilamsy

The main changes are:

- Change project from tabs to spaces, in line with IDE defaults.
- Removed a leftover check from the buildscript.
- Added spaces after commas and ifs. Why, Martin?
- Renamed some methods to make more sense. Why are they named internal if they have no default impl?
  - `changeEnergy` to `adjustEnergy`
- Added some documentation where it was glaringly missing.
- Removed energy network type as it's entirely unused.
- Renamed `base` package to `templates` to be in line with what StAPI does.

2024-11-07 17:50 UTC, MartinSVK12 commented on src/main/java/net/teamterminus/machineessentials/network/NetworkWalker.java
> + * This class uses <code>INetworkWire</code> to differentiate between the medium (wires) and endpoints (devices) of a network to build paths.
How did the "I" get here again

2024-11-07 17:54 UTC, MartinSVK12 requested changes
Just one small regression in `NetworkWalker`s javadoc, otherwise fine i guess?

2024-11-07 18:48 UTC, MartinSVK12 commented
Okay, fixed that.

2024-11-07 18:49 UTC, MartinSVK12 approved these changes

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +        if (amperage > getMaxInputAmperage()){
If we are talking about putting spaces everywhere then we also should put space here after `if ()`

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +                if (path.target == this || !(path.target instanceof Electric dest)){
Also space here after `if ()`

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +                            if (component instanceof ElectricWire pathWire){
And also space here after `if ()`

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +                        if (pathLoss >= voltage){
Aaaannd here

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +                            if (pathBlockEntity instanceof ElectricWire pathWire){
As well as these  2 IFs on 75 and 76

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> -                        if(pathVoltage > 0){
Maybe also here?xD

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
> +                            if (pathVoltage > getMaxInputVoltage()){
I love that there's so many of them. Gotta have so much fun writing these comments

2024-11-08 09:26 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/network/NetworkWalker.java
> +    public static <T extends NetworkComponent> List<NetworkPath> createNetworkPaths(World world, Vec3i source){
Missing some spaces after `if ()` here

2024-11-08 09:39 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
>      public long receiveEnergy(@NotNull Direction dir, long amperage) {
Oh my god why there's so many IFs? This is such big nest of IFs

2024-11-08 09:39 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
>      public long receiveEnergy(@NotNull Direction dir, long amperage) {
In this method I mean. Just look at the end of the method there's at least like 10 closing brackets before `return` and the end of the method

2024-11-08 15:21 UTC, merged

2024-11-08 15:23 UTC, MrMasrozYTLIVE commented on src/main/java/net/teamterminus/machineessentials/energy/electric/template/ElectricDeviceBlockEntity.java
>      public long receiveEnergy(@NotNull Direction dir, long amperage) {
> @MartinSVK12 's problem.

I've fixed it and could've push but right now I am not at my pc so ehhh